[phases.setup]
apt_packages = ["python3", "python3-pip"]

[phases.install]
commands = ["pip install -r requirements.txt"]

[phases.start]
commands = ["python manage.py migrate", "python manage.py runserver 0.0.0.0:$PORT"]
