[phases.setup]
apt_packages = ["python", "python-pip"]

[phases.install]
commands = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
commands = ["python manage.py migrate"]

[phases.start]
commands = ["python manage.py runserver 0.0.0.0:${PORT}"]

[languages.python]
version = "3.9"  # Or specify the exact Python version your project requires
