[phases.setup]
apt_packages = ["python3", "python3-pip"]

[phases.install]
commands = ["python3 -m pip install --upgrade pip", "pip3 install -r requirements.txt"]

[phases.build]
commands = ["python3 manage.py migrate"]

[phases.start]
commands = ["python3 manage.py runserver 0.0.0.0:${PORT}"]

[languages.python]
version = "3.12"
